#pragma once
//#include <GameData/Packets\Server/ChangeAttributesScrollData.h>
//#include <GameData/Packets\Client/NpcTalkEnchantUnknownPacket.h>
//#include <GameData/Packets\Client/ReconnectPacket.h>
//#include <GameData/Packets\Server/TradeErrorPacket.h>
//#include <GameData/Packets\Client/StateSkillPacket.h>
//#include <GameData/Packets\Server/ChangeAttributesScrollUseScrollPacket.h>
//#include <GameData/Packets\Client/ResponseVersionPacket.h>
//#include <GameData/Packets\Client/NpcTalkNextQuestPacket.h>
//#include <GameData/Packets\Client/ResponseHeartbeatPacket.h>
//#include <GameData/Packets\Client/NpcTalkClosePacket.h>
//#include <GameData/Packets\Client/HandshakePacket.h>
//#include <GameData/Packets\Server/ItemEnchantErrorPacket.h>
//#include <GameData/Packets\Server/ItemLockUpdateItemPacket.h>
//#include <GameData/Packets\Server/TradeDeclinedPacket.h>
//#include <GameData/Packets\Client/NpcTalkBeginPacket.h>
//#include <GameData/Packets\Server/PlayInstrumentPlayNotePacket.h>
//#include <GameData/Packets\Client/LogInPacket.h>
//#include <GameData/Packets\Client/NpcTalkContinuePacket.h>
//#include <GameData/Packets\Client/LogInAuthTokenPacket.h>
//#include <GameData/Packets\Client/ResponseKeyPacket.h>
//#include <GameData/Packets\Client/NpcTalkAllianceQuestAcceptPacket.h>
//#include <GameData/Packets\Client/RequestQuitPacket.h>
//#include <GameData/Packets\Client/NpcTalkAllianceQuestTalkPacket.h>
//#include <GameData/Packets\Client/SkillCastPacket.h>
//#include <GameData/Packets\Client/NpcTalkCinematicPacket.h>
//#include <GameData/Packets\Client/SkillSyncDamagePacket.h>
//#include <GameData/Packets\Client/SystemInfoData.h>
//#include <GameData/Packets\Server/FittingDollData.h>
//#include <GameData/Packets\Client/SkillData.h>
//#include <GameData/Packets\Server/ServerEnterData.h>
//#include <GameData/Packets\Server/SkillData.h>
//#include <GameData/Packets\Server/FieldRemoveNpcData.h>
//#include <GameData/Packets\Server/FieldAddPlayerData.h>
//#include <GameData/Packets\Server/FurnishingStorageData.h>
//#include <GameData/Packets\Server/ShopData.h>
//#include <GameData/Packets\Server/Reconnect7Data.h>
//#include <GameData/Packets\Server/ItemSkinPutOffData.h>
//#include <GameData/Packets\Server/NpcTalkServerData.h>
//#include <GameData/Packets\Server/CharacterListData.h>
//#include <GameData/Packets\Server/MailData.h>
//#include <GameData/Packets\Server/JobPacket.h>
//#include <GameData/Packets\Server/CharacterListCancelDeletePacket.h>
//#include <GameData/Packets\Server/MailErrorPacket.h>
//#include <GameData/Packets\Server/ItemLockAddItemPacket.h>
//#include <GameData/Packets\Server/UserChatPacket.h>
//#include <GameData/Packets\Server/ItemLockRemoveItemPacket.h>
//#include <GameData/Packets\Server/TrophyUpdatePacket.h>
//#include <GameData/Packets\Server/ItemLockErrorPacket.h>
//#include <GameData/Packets\Server/MailEndListPacket.h>
//#include <GameData/Packets\Server/MailError2Packet.h>
//#include <GameData/Packets\Server/FurnishingStorageCountPacket.h>
//#include <GameData/Packets\Server/MailReceiveGiftNotificationPacket.h>
//#include <GameData/Packets\Server/UserChatItemLinkPacket.h>
//#include <GameData/Packets\Server/FieldAddNpcPacket.h>
//#include <GameData/Packets\Server/RequestFieldEnterPacket.h>
//#include <GameData/Packets\Server/FieldRemovePlayerPacket.h>
//#include <GameData/Packets\Server/FurnishingStorageStartListPacket.h>
//#include <GameData/Packets\Server/FurnishingStoragePurchasePacket.h>
//#include <GameData/Packets\Server/FurnishingStorageUpdatePacket.h>
//#include <GameData/Packets\Server/FurnishingStorageEndListPacket.h>
//#include <GameData/Packets\Server/ItemPutOnPacket.h>
//#include <GameData/Packets\Server/ItemPutOffPacket.h>
//#include <GameData/Packets\Server/ItemSkinPutOnPacket.h>
//#include <GameData/Packets\Server/ItemUpdatePacket.h>
//#include <GameData/Packets\Server/FieldAddItemPacket.h>
//#include <GameData/Packets\Server/LoadCubesPacket.h>
//#include <GameData/Packets\Server/LoadCubesAvailabilityPacket.h>
//#include <GameData/Packets\Server/LoadCubesPlotsPacket.h>
//#include <GameData/Packets\Server/LoadCubesExpirationPacket.h>
//#include <GameData/Packets\Server/FieldRemoveItemPacket.h>
//#include <GameData/Packets\Server/StatPacket.h>
//#include <GameData/Packets\Server/ExpUpPacket.h>
//#include <GameData/Packets\Server/LevelUpPacket.h>
//#include <GameData/Packets\Server/BlackMarketMyListingsPacket.h>
//#include <GameData/Packets\Server/BindItemPacket.h>
//#include <GameData/Packets\Server/SkillDamageSyncPacket.h>
//#include <GameData/Packets\Server/SkillDamageDotPacket.h>
//#include <GameData/Packets\Server/SkillDamageHealPacket.h>
//#include <GameData/Packets\Server/SkillDamageRegionPacket.h>
//#include <GameData/Packets\Server/SkillDamageTilePacket.h>
//#include <GameData/Packets\Server/BuffPacket.h>
//#include <GameData/Packets\Server/PetInventoryMoveItemPacket.h>
//#include <GameData/Packets\Server/ChangeAttributesPreviewPacket.h>
//#include <GameData/Packets\Server/PetInfoPacket.h>
//#include <GameData/Packets\Server/ChangeAttributesAddPacket.h>
//#include <GameData/Packets\Server/TrophyContentPacket.h>
//#include <GameData/Packets\Server/ChangeAttributesScrollPreviewItemPacket.h>
//#include <GameData/Packets\Server/ChangeAttributesErrorPacket.h>
//#include <GameData/Packets\Server/ShopOpenPacket.h>
//#include <GameData/Packets\Server/ShopLoadItemsPacket.h>
//#include <GameData/Packets\Server/ShopUpdatePacket.h>
//#include <GameData/Packets\Server/ShopBuyPacket.h>
//#include <GameData/Packets\Server/ShopBuyBackItemCountPacket.h>
//#include <GameData/Packets\Server/ShopAddBuyBackPacket.h>
//#include <GameData/Packets\Server/ShopRemoveBuyBackPacket.h>
//#include <GameData/Packets\Server/ShopInstantRestockPacket.h>
//#include <GameData/Packets\Server/ShopMeretItemCountPacket.h>
//#include <GameData/Packets\Server/ShopLoadMeretItemPacket.h>
//#include <GameData/Packets\Server/ShopErrorPacket.h>
//#include <GameData/Packets\Server/FieldAddPetPacket.h>
//#include <GameData/Packets\Server/FieldRemovePetPacket.h>
//#include <GameData/Packets\Server/TrophyStartPacket.h>
//#include <GameData/Packets\Server/PetRenamePacket.h>
//#include <GameData/Packets\Server/CharacterInfoPacket.h>
//#include <GameData/Packets\Server/PlayInstrumentViewMusicPacket.h>
//#include <GameData/Packets\Server/FittingDollLoadPacket.h>
//#include <GameData/Packets\Server/PetLootPacket.h>
//#include <GameData/Packets\Server/FittingDollRemovePacket.h>
//#include <GameData/Packets\Server/FittingDollPutOnItemPacket.h>
//#include <GameData/Packets\Server/FittingDollRemoveItemPacket.h>
//#include <GameData/Packets\Server/TradeReceiveRequestPacket.h>
//#include <GameData/Packets\Server/PetFusionDialogPacket.h>
//#include <GameData/Packets\Server/TradeConfirmRequestPacket.h>
//#include <GameData/Packets\Server/PetOtherPetInfoPacket.h>
//#include <GameData/Packets\Server/TradeBeginPacket.h>
//#include <GameData/Packets\Server/TradeEndPacket.h>
//#include <GameData/Packets\Server/TradeAddItemPacket.h>
//#include <GameData/Packets\Server/TradeRemoveItemPacket.h>
//#include <GameData/Packets\Server/TradeSetMoneyPacket.h>
//#include <GameData/Packets\Server/TradeFinalizePacket.h>
//#include <GameData/Packets\Server/PetInventoryStoreItemPacket.h>
//#include <GameData/Packets\Server/TradeChangeOfferPacket.h>
//#include <GameData/Packets\Server/TradeFinalizeConfirmPacket.h>
//#include <GameData/Packets\Server/PetInventoryUpdateAmountPacket.h>
//#include <GameData/Packets\Server/ItemEnchantBeginPacket.h>
//#include <GameData/Packets\Server/ItemEnchantUpdateExpPacket.h>
//#include <GameData/Packets\Server/ItemEnchantUpdateChargesPacket.h>
//#include <GameData/Packets\Server/ItemEnchantUpdateIngredientsPacket.h>
//#include <GameData/Packets\Server/ItemEnchantSuccessPacket.h>
//#include <GameData/Packets\Server/ItemEnchantFailPacket.h>
//#include <GameData/Packets\Server/ChangeAttributesScrollApplyPacket.h>
//#include <GameData/Packets\Server/BlackMarketErrorPacket.h>
//#include <GameData/Packets\Server/PetEvolvePointsPacket.h>
//#include <GameData/Packets\Server/BlackMarketCreateListingPacket.h>
//#include <GameData/Packets\Server/BlackMarketCancelListingPacket.h>
//#include <GameData/Packets\Server/BlackMarketSearchResultsPacket.h>
//#include <GameData/Packets\Server/BlackMarketPurchasePacket.h>
//#include <GameData/Packets\Server/BlackMarketSoldPacket.h>
//#include <GameData/Packets\Server/BlackMarketPrepareListingPacket.h>
//#include <GameData/Packets\Server/PetLoadCollectionPacket.h>
//#include <GameData/Packets\Server/EnchantScrollEnchantUiPacket.h>
//#include <GameData/Packets\Server/EnchantScrollStatUiPacket.h>
//#include <GameData/Packets\Server/PetInventoryListItemsPacket.h>
//#include <GameData/Packets\Server/EnchantScrollSuccessPacket.h>
//#include <GameData/Packets\Server/EnchantScrollResultPacket.h>
//#include <GameData/Packets\Server/EnchantScrollRewardPacket.h>
//#include <GameData/Packets\Server/PlayInstrumentStartImprovisePacket.h>
//#include <GameData/Packets\Server/PlayInstrumentStopImprovisePacket.h>
//#include <GameData/Packets\Server/PetEvolvePacket.h>
//#include <GameData/Packets\Server/PlayInstrumentStartScorePacket.h>
//#include <GameData/Packets\Server/PetAddPacket.h>
//#include <GameData/Packets\Server/PlayInstrumentStopScorePacket.h>
//#include <GameData/Packets\Server/PlayInstrumentLeaveEnsemblePacket.h>
//#include <GameData/Packets\Server/PlayInstrumentCreateScoreResponsePacket.h>
//#include <GameData/Packets\Server/PlayInstrumentUpdateScoreUsesPacket.h>
//#include <GameData/Packets\Server/PlayInstrumentEffectPacket.h>
//#include <GameData/Packets\Server/PlayInstrumentWritePlayDialogPacket.h>
//#include <GameData/Packets\Server/ChangeAttributesScrollUseOnItemPacket.h>
//#include <GameData/Packets\Server/PetRemovePacket.h>
//#include <GameData/Packets\Server/PetSoundPacket.h>
//#include <GameData/Packets\Server/PetPotionPacket.h>
//#include <GameData/Packets\Server/PetAddCollectionPacket.h>
//#include <GameData/Packets\Server/PetFusionPacket.h>
//#include <GameData/Packets\Server/PetLevelUpPacket.h>
//#include <GameData/Packets\Server/PetSummonedNoticePacket.h>
//#include <GameData/Packets\Server/PetErrorPacket.h>
//#include <GameData/Packets\Server/PetLapisSnarePacket.h>
//#include <GameData/Packets\Server/PetUnknownFieldPetPacket.h>
//#include <GameData/Packets\Server/PetInventoryRemoveItemPacket.h>
//#include <GameData/Packets\Server/PetInventoryStartListPacket.h>
//
#include <GameData/Packets\Client/HandshakeData.h>
#include <GameData/Packets\Client/LogInData.h>
#include <GameData/Packets\Client/LogInAuthTokenData.h>
#include <GameData/Packets\Client/NpcTalkClientData.h>
#include <GameData/Packets\Client/ReconnectData.h>
#include <GameData/Packets\Client/RequestQuitData.h>
#include <GameData/Packets\Client/ResponseHeartbeatData.h>
#include <GameData/Packets\Client/ResponseKeyData.h>
#include <GameData/Packets\Client/ResponseVersionData.h>
#include <GameData/Packets\Client/SkillData.h>
#include <GameData/Packets\Client/StateSkillData.h>
#include <GameData/Packets\Client/SystemInfoData.h>
#include <GameData/Packets\Server/BindItemData.h>
#include <GameData/Packets\Server/BlackMarketData.h>
#include <GameData/Packets\Server/BuffData.h>
#include <GameData/Packets\Server/ChangeAttributesData.h>
#include <GameData/Packets\Server/ChangeAttributesData.h>
#include <GameData/Packets\Server/CharacterInfoData.h>
#include <GameData/Packets\Server/CharacterListData.h>
#include <GameData/Packets\Server/EnchantScrollData.h>
#include <GameData/Packets\Server/ExpUpData.h>
#include <GameData/Packets\Server/FieldAddItemData.h>
#include <GameData/Packets\Server/FieldAddNpcData.h>
#include <GameData/Packets\Server/FieldAddPetData.h>
#include <GameData/Packets\Server/FieldAddPlayerData.h>
#include <GameData/Packets\Server/FieldRemoveItemData.h>
#include <GameData/Packets\Server/FieldRemoveNpcData.h>
#include <GameData/Packets\Server/FieldRemovePetData.h>
#include <GameData/Packets\Server/FieldRemovePlayerData.h>
#include <GameData/Packets\Server/FittingDollData.h>
#include <GameData/Packets\Server/FurnishingStorageData.h>
#include <GameData/Packets\Server/ItemEnchantData.h>
#include <GameData/Packets\Server/ItemLockData.h>
#include <GameData/Packets\Server/ItemPutOffData.h>
#include <GameData/Packets\Server/ItemPutOnData.h>
#include <GameData/Packets\Server/ItemSkinPutOffData.h>
#include <GameData/Packets\Server/ItemSkinPutOnData.h>
#include <GameData/Packets\Server/ItemUpdateData.h>
#include <GameData/Packets\Server/JobData.h>
#include <GameData/Packets\Server/LevelUpData.h>
#include <GameData/Packets\Server/LoadCubesData.h>
#include <GameData/Packets\Server/MailData.h>
#include <GameData/Packets\Server/NpcTalkServerData.h>
#include <GameData/Packets\Server/PetData.h>
#include <GameData/Packets\Server/PetData.h>
#include <GameData/Packets\Server/PlayInstrumentData.h>
#include <GameData/Packets\Server/Reconnect7Data.h>
#include <GameData/Packets\Server/RequestFieldEnterData.h>
#include <GameData/Packets\Server/ServerEnterData.h>
#include <GameData/Packets\Server/ShopData.h>
#include <GameData/Packets\Server/SkillData.h>
#include <GameData/Packets\Server/StatData.h>
#include <GameData/Packets\Server/TradeData.h>
#include <GameData/Packets\Server/TrophyData.h>
#include <GameData/Packets\Server/UserChatData.h>
#include <GameData/Packets\Server/UserChatItemLinkData.h>
